title: CHIST-ERA project "Interactive Grounded Language Understanding"
description: "Project IGLU-CHISTERA Public Website "
google_analytics:
show_downloads: false
theme: minima

gems:
  - jekyll-mentions
  - minima
